// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MHD_cpp
NumericVector MHD_cpp(NumericMatrix D);
RcppExport SEXP _MetricDepth_MHD_cpp(SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(MHD_cpp(D));
    return rcpp_result_gen;
END_RCPP
}
// MHD_test_cpp
double MHD_test_cpp(NumericMatrix D, NumericVector d);
RcppExport SEXP _MetricDepth_MHD_test_cpp(SEXP DSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(MHD_test_cpp(D, d));
    return rcpp_result_gen;
END_RCPP
}
// MLD_cpp
NumericVector MLD_cpp(NumericMatrix D);
RcppExport SEXP _MetricDepth_MLD_cpp(SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(MLD_cpp(D));
    return rcpp_result_gen;
END_RCPP
}
// MOD2_cpp
NumericVector MOD2_cpp(NumericMatrix D);
RcppExport SEXP _MetricDepth_MOD2_cpp(SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(MOD2_cpp(D));
    return rcpp_result_gen;
END_RCPP
}
// det3times3_cpp
double det3times3_cpp(NumericMatrix M);
RcppExport SEXP _MetricDepth_det3times3_cpp(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(det3times3_cpp(M));
    return rcpp_result_gen;
END_RCPP
}
// MOD3_cpp
NumericVector MOD3_cpp(NumericMatrix D);
RcppExport SEXP _MetricDepth_MOD3_cpp(SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(MOD3_cpp(D));
    return rcpp_result_gen;
END_RCPP
}
// MOD3_test_cpp
double MOD3_test_cpp(NumericMatrix D, NumericVector d);
RcppExport SEXP _MetricDepth_MOD3_test_cpp(SEXP DSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(MOD3_test_cpp(D, d));
    return rcpp_result_gen;
END_RCPP
}
// MSD_cpp
NumericVector MSD_cpp(NumericMatrix D);
RcppExport SEXP _MetricDepth_MSD_cpp(SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(MSD_cpp(D));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _MetricDepth_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MetricDepth_MHD_cpp", (DL_FUNC) &_MetricDepth_MHD_cpp, 1},
    {"_MetricDepth_MHD_test_cpp", (DL_FUNC) &_MetricDepth_MHD_test_cpp, 2},
    {"_MetricDepth_MLD_cpp", (DL_FUNC) &_MetricDepth_MLD_cpp, 1},
    {"_MetricDepth_MOD2_cpp", (DL_FUNC) &_MetricDepth_MOD2_cpp, 1},
    {"_MetricDepth_det3times3_cpp", (DL_FUNC) &_MetricDepth_det3times3_cpp, 1},
    {"_MetricDepth_MOD3_cpp", (DL_FUNC) &_MetricDepth_MOD3_cpp, 1},
    {"_MetricDepth_MOD3_test_cpp", (DL_FUNC) &_MetricDepth_MOD3_test_cpp, 2},
    {"_MetricDepth_MSD_cpp", (DL_FUNC) &_MetricDepth_MSD_cpp, 1},
    {"_MetricDepth_rcpp_hello_world", (DL_FUNC) &_MetricDepth_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_MetricDepth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
