# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MHD_cpp <- function(D) {
    .Call(`_MetricDepth_MHD_cpp`, D)
}

MHD_test_cpp <- function(D, d) {
    .Call(`_MetricDepth_MHD_test_cpp`, D, d)
}

MLD_cpp <- function(D) {
    .Call(`_MetricDepth_MLD_cpp`, D)
}

MOD2_cpp <- function(D) {
    .Call(`_MetricDepth_MOD2_cpp`, D)
}

det3times3_cpp <- function(M) {
    .Call(`_MetricDepth_det3times3_cpp`, M)
}

MOD3_cpp <- function(D) {
    .Call(`_MetricDepth_MOD3_cpp`, D)
}

MOD3_test_cpp <- function(D, d) {
    .Call(`_MetricDepth_MOD3_test_cpp`, D, d)
}

MSD_cpp <- function(D) {
    .Call(`_MetricDepth_MSD_cpp`, D)
}

rcpp_hello_world <- function() {
    .Call(`_MetricDepth_rcpp_hello_world`)
}

